<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260123092348 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE delivery (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, reference VARCHAR(64) NOT NULL, status VARCHAR(32) NOT NULL, pickup_address VARCHAR(255) NOT NULL, dropoff_address VARCHAR(255) NOT NULL, planned_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, vendor_id INT NOT NULL, buyer_id INT NOT NULL, white_label_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3781EC10F603EE73 ON delivery (vendor_id)');
        $this->addSql('CREATE INDEX IDX_3781EC106C755722 ON delivery (buyer_id)');
        $this->addSql('CREATE INDEX IDX_3781EC103D57AF5A ON delivery (white_label_id)');
        $this->addSql('ALTER TABLE delivery ADD CONSTRAINT FK_3781EC10F603EE73 FOREIGN KEY (vendor_id) REFERENCES organization (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE delivery ADD CONSTRAINT FK_3781EC106C755722 FOREIGN KEY (buyer_id) REFERENCES organization (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE delivery ADD CONSTRAINT FK_3781EC103D57AF5A FOREIGN KEY (white_label_id) REFERENCES white_label (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE delivery DROP CONSTRAINT FK_3781EC10F603EE73');
        $this->addSql('ALTER TABLE delivery DROP CONSTRAINT FK_3781EC106C755722');
        $this->addSql('ALTER TABLE delivery DROP CONSTRAINT FK_3781EC103D57AF5A');
        $this->addSql('DROP TABLE delivery');
    }
}
