<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260121150939 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE app_user (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, azure_id VARCHAR(255) DEFAULT NULL, organization_id INT DEFAULT NULL, white_label_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_88BDF3E9E7927C74 ON app_user (email)');
        $this->addSql('CREATE INDEX IDX_88BDF3E932C8A3DE ON app_user (organization_id)');
        $this->addSql('CREATE INDEX IDX_88BDF3E93D57AF5A ON app_user (white_label_id)');
        $this->addSql('ALTER TABLE app_user ADD CONSTRAINT FK_88BDF3E932C8A3DE FOREIGN KEY (organization_id) REFERENCES organization (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE app_user ADD CONSTRAINT FK_88BDF3E93D57AF5A FOREIGN KEY (white_label_id) REFERENCES white_label (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE app_user DROP CONSTRAINT FK_88BDF3E932C8A3DE');
        $this->addSql('ALTER TABLE app_user DROP CONSTRAINT FK_88BDF3E93D57AF5A');
        $this->addSql('DROP TABLE app_user');
    }
}
